name: Bun CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JSB_PUBLIC_KEY: ${{ secrets.JSB_PUBLIC_KEY }}
      JSB_PRIVATE_KEY: ${{ secrets.JSB_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test
